# Site settings
title: Douglas
index_title: Douglas Lopes # same as title in index.html file, so that custom description can be set in page.html layout.
blog_title: Douglas Lopes Architecture
header-img: img/home-bg.jpg
email: douglaslopes@live.com
copyright_name: Douglas Lopes
description: ""A vida é um sopro" - Oscar Niemeyer"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
url: http://douglasvlopes.github.io/ #only used in disque comments for now
disqus_url: douglasvlopes.github.io/ # disque comments are broken if you send http:// along with url
github_username:  douglasvlopes
facebook_username:  https://www.facebook.com/douglas.lopes.3154?ref=bookmarks
email_username:  douglaslopes@live.com
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed]
